### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by mazeeblanke** [sergiodxa/next-nprogress#102] opened 2019-08-07 09:12 UTC
After following the installation steps i get the following error:

Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at sanitize (C:\Users\mazino.ukah\ReactProjects\Treten\TretenFE\node_modules\styled-jsx\dist\stylesheet-registry.js:21:15)

**Comment by Protectator** [comment] 2019-08-29 08:28
This is a duplicate of https://github.com/sergiodxa/next-nprogress/issues/76

**Comment by sergiodxa** [comment] 2020-02-28 15:05
Hello,

I'm not maintaining this anymore because I'm not using it anymore in my projects and I don't have time to work on it.

Feel free to fork and publish to npm with another name.

**Closed as completed by sergiodxa** 2020-02-28 15:05 UTC
